language: android

android:
    components:
        - build-tools-19.1.0
    licences:
        - android-sdk-license-5be876d5

branches:
    only:
        - master

env:
    global:
        # ORG_GRADLE_PROJECT_MAVEN_USER environment variable:
        - secure: "ABfWncM08+CcuUCU9sUa3SFVVFHxclEdHMJ3fE/vT1rqJP/xuDPOaV3hzBNhPnXji1iaXfMxomLDWLLKEe4bwAYukNm4FJBX9zDFamcSxmk4Mq6xGiR/P9NlNQ7mDJ2noixQqER8A/6xRAVRphl+4X6y0GFgqFpb2m2vk5ZabtE="
        # ORG_GRADLE_PROJECT_MAVEN_PASS environment variable:
        - secure: "I4L0mpR7cQFooDW85UvNRkdHebIjFDR5EvXg5N+KGu+8pZvkf9eW3OncX3nAs9O09f85cfE73UOK7Dn58s3HIAo6gJZW9hwCakSAqsaB/dv7H87+UxVPxCn+0nJLQaUtlqwFmsC/1Bwm6E7tdR5Py1iW+tbueo46DaVVuJViVa4="

before_install:
    - echo no | android create avd --force --name test-avd --target android-19 --abi armeabi-v7a
    - emulator -avd test-avd -no-skin -no-audio -no-window &

script:
    - ./gradlew assemble
    - ./wait_for_emulator.sh
    - ./gradlew connectedCheck
